# fly.toml app configuration file generated for geobeermap-cms on 2023-07-24T16:23:45+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "geobeermap-cms"
primary_region = "otp"

[env]
PORT = "1337"



[[services]]
  http_checks = []
  internal_port = 1337
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 3
    timeout = "3s"
  
  # [http_service]
  #   internal_port = 1337
  #   force_https = true
  #   auto_stop_machines = true
  #   auto_start_machines = true
  #   min_machines_running = 0
  #   processes = ["app"]